### ISSUE TITLE
sw:plugin:update creates php warning

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#12]
installed the plugin and used sw:plugin:update from sw console --shell, got:

PHP Warning:  Declaration of Shopware\CustomModels\MoptPayoneConfig\MoptPayoneConfig::fromArray($array = Array) should be compatible with Shopware\Components\Model\ModelEntity::fromArray(array $array = Array) in /var/www/admin.dev.b2c/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Models/MoptPayoneConfig/MoptPayoneConfig.php on line 1274

Plugin MoptPaymentPayone has been updated successfully.

**Comment by fjbender** [comment]
Already fixed with #3 but not in the package.

**Comment by Fatchip-Support** [comment]
The warning is  fixed with new [commit ](https://github.com/PAYONE-GmbH/shopware-5/commit/58ff3e7e43cd9064522410b939e4af20cb11a819)

**Comment by Fatchip-Support** [comment]
should be fixed with Zip Package
FatchipPayoneConnector_v3.3.8_5657_shopware5_source.zip
