### ISSUE TITLE
Performance (Subscribers) sGetBasket

### ISSUE THREAD

**Issue by pdornbusch** [PAYONE-GmbH/shopware-5#125]
Hi, 

please consider replacing calls toShopware()->Modules()->Basket()->sGetBasket() with Shopware()->Modules()->Basket()->sGetBasketData() where possible. 

As a call to sGetBasket() will always trigger a recalculation of the whole basket and executes all attached subscribers again. This is not a big problem at all for small baskets with 5 to 10 items but has an large impact for baskets with more than 20 items.

**Comment by fjbender** [comment]
Thanks for the suggestion! Does sGetBasketData() have any drawbacks in comparison with sGetBasket()?

**Comment by pdornbusch** [comment]
sGetBasket() always calls sUpdateArticle for each basket position and recalculates surchages, discounts, vouchers ans so on. 

IMHO you should check if sGetBasket or sUpdateArticle was called within the dispatch process before.

**Comment by fjbender** [comment]
We have now a pull request for this issue: https://github.com/PAYONE-GmbH/shopware-5/pull/130

@pdornbusch Can you confirm that this is a viable approach?

Cheers
Florian

**Comment by pdornbusch** [comment]
@fjbender looks good! We used a hash for the cart content in our approach to reduce the subscriber count but your approach seems more stable.

Best,
Patrick
