### ISSUE TITLE
Fatal error: Uncaught Error: Unsupported operand types in .../engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Subscribers/FrontendAccount.php:70

### ISSUE THREAD

**Issue by AndreasBielmeier** [PAYONE-GmbH/shopware-5#127]
Installed plugin version is 3.6.0, Shopware Version 5.2.27.

I have registered a new account in shopware (completely new, no checkout, no order), then i clicked on my account and payment types, the following error occurs:
Fatal error: Uncaught Error: Unsupported operand types in .../engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Subscribers/FrontendAccount.php:70
Stack trace: 
#0 .../engine/Library/Enlight/Event/Handler/Default.php(91): Shopware\Plugins\MoptPaymentPayone\Subscribers\FrontendAccount->onPaymentAction(Object(Enlight_Hook_HookArgs)) 
#1 .../engine/Library/Enlight/Event/EventManager.php(296): Enlight_Event_Handler_Default->execute(Object(Enlight_Hook_HookArgs)) 
#2 .../engine/Library/Enlight/Hook/HookManager.php(191): Enlight_Event_EventManager->filter('Shopware_Contro...', NULL, Object(Enlight_Hook_HookArgs)) 
#3 .../var/cache/production_201707131430/proxies/ShopwareControllersFrontendAccountProxy.php(17): Enlight_Hook_HookManager->executeHooks(Object(Shopware_Proxies_ShopwareControllersFrontendAccountProxy), 'paymentAction', Object(Enlight_Hook_HookArgs)) 
#4 .../engine/Library/Enlight/Controller/Action.php(159 in .../engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Subscribers/FrontendAccount.php on line 70

I think the line "$subject->View()->sUserData += $paymentData;" has to be within the not empty if.

**Comment by fjbender** [comment]
I could reproduce this issue. We'll look into that and issue a fix.

Thanks
Florian

**Comment by mpathy** [comment]
We have that too and are only days from going live.. Hope you can fix this soon!

**Comment by T-Kuchel** [comment]
Sorry! It is already fixed with https://github.com/PAYONE-GmbH/shopware-5/pull/128

**Comment by AndreasBielmeier** [comment]
Thanks a lot. When will be the update available in shopware plugin store?
