### ISSUE TITLE
uninstall routine causes issues 

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#13]
uninstall plugin and try to reinstall, this causes

Unable to install, got exception: An exception occurred while executing 'INSERT INTO s_core_menu (name, onclick, style, class, position, active, pluginID, controller, action, shortcut, parent) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["PAYONE Kontrollzentrum", "Shopware.ModuleManager.createSimplifiedModule(\"FcPayone\", { \"title\": \"PAYONE Kontrollzentrum\" })", null, "payoneicon", 0, 1, 67, null, null, null, 65]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'PAYONE Kontrollzentrum-65' for key 'name'

**Comment by Fatchip-Support** [comment]
should be fixed with Zip Package
FatchipPayoneConnector_v3.3.8_5657_shopware5_source.zip
