### ISSUE TITLE
Could you make the default styles for hosted iFrame more usable?

### ISSUE THREAD

**Issue by lumpi2k** [PAYONE-GmbH/shopware-5#134]
Hi there,

I noticed the default styles that come with new installations don't really work even with the standard template. I had a look at the defaults and found that the iframe heights don't really match the height of the fields in them with the standard CSS.

![before](https://user-images.githubusercontent.com/32732790/31487945-7324250a-af3c-11e7-982e-12d40971e788.JPG)

Could you alter the defaults so that the standard height of the iframes is 40px? This alone would go a long way to a useable standard. While you're at it, making the width of the expiremonth 80px and expireyear 90px would also look great. And I think the width of the cardpan field should be 100% rather than 100px to match the width of the name above. Finally, adding a "border-radius:3px;" to the standard CSS would perfectly match the default styles of the surrounding fields.

![after](https://user-images.githubusercontent.com/32732790/31488106-02972e44-af3d-11e7-9e0b-6d9c03693b13.JPG)

I found the line in which the standards are written to the db but I'm not familiar with pull requests or anything so all I can do is open this issue. Thanks in advance!

https://github.com/PAYONE-GmbH/shopware-5/blob/67916787bd517ecc416ee21f0daf45695d9a5098/Frontend/MoptPaymentPayone/Components/Classes/PayoneInstallHelper.php#L717

**Comment by fjbender** [comment]
It's a no brainer, we'll do it :)

**Comment by fjbender** [comment]
Fixed in #136. Please note that this change only takes effect when freshly installing the Plugin or truncating the credit card config table before the update.
