### ISSUE TITLE
installing and activating the plugin causes fatal error

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#14]
installed the plugin, tried to activate it, caused:

Fatal error: Uncaught TypeError: Argument 1 passed to Shopware\Plugins\MoptPaymentPayone\Subscribers\AddressCheck::__construct() must be an instance of Shopware\Plugins\MoptPaymentPayone\Subscribers\Container, instance of ShopwareProductionProjectContainer given, called in /var/www/XX.XX.XX/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Bootstrap.php on line 336 and defined in /var/www/XX.XX.XX/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Subscribers/AddressCheck.php:23 Stack trace: #0 /var/www/XX.XX.XX/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Bootstrap.php(336): Shopware\Plugins\MoptPaymentPayone\Subscribers\AddressCheck->__construct(Object(ShopwareProductionProjectContainer)) #1 /var/www/XX.XX.XX/htdocs/engine/Library/Enlight/Event/Handler/Plugin.php(149): Shopware_Plugins_Frontend_MoptPaymentPayone_Bootstrap->onDispatchLoopStartup(Object(Enlight_Controller_EventArgs)) #2 /var/www/XX.XX.XX/htdocs/engine/Library/Enlight/Event/ in /var/www/XX.XX.XX/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Subscribers/AddressCheck.php on line 23
503 Service Unavailable

**Comment by fjbender** [comment]
Should already be fixed, cf: https://github.com/PAYONE-GmbH/shopware-5/blob/master/Frontend/MoptPaymentPayone/Subscribers/AddressCheck.php#L23

@Fatchip-Support can you verify?

**Comment by fjbender** [comment]
It's fixed in the source tree, but not in the package. Please build a new package.

**Comment by Fatchip-Support** [comment]
Verified, new Package is coming

**Comment by Fatchip-Support** [comment]
should be fixed with Zip Package
FatchipPayoneConnector_v3.3.8_5657_shopware5_source.zip
