### ISSUE TITLE
Fatal error: Uncaught Error: Unsupported operand types in MoptPaymentPayone/Subscribers/FrontendAccount.php:70

### ISSUE THREAD

**Issue by shyim** [PAYONE-GmbH/shopware-5#144]
Hey,
we found a issue with the account payment switcher while the payone plugin is active. I guess the problem is the usage of += which throws a fatal error on php7.

PHP: 7.0.24
Plugin Version: 3.6.0

**Comment by fjbender** [comment]
I guess we have this already fixed with #127. However, that fix is not yet live in the Shopware Community Store. I'll attend to that.
