### ISSUE TITLE
Fatal error: Uncaught Error: Unsupported operand types in /var/www/html/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Subscribers/FrontendAccount.php on line 70

### ISSUE THREAD

**Issue by Forestsoft-de** [PAYONE-GmbH/shopware-5#152]
https://github.com/PAYONE-GmbH/shopware-5/blob/67916787bd517ecc416ee21f0daf45695d9a5098/Frontend/MoptPaymentPayone/Subscribers/FrontendAccount.php#L69

Shopware 5.2.26 und PHP 7.0.14

paymentData ist bei uns false

**Comment by fjbender** [comment]
Das sollte eigentlich mit #133 gefixt worden sein. Welche Modulversion setzt du ein?

**Comment by Forestsoft-de** [comment]
Muss ich checken.
