### ISSUE TITLE
MoptShopNotification::indexAction creates duplicate entries in order table

### ISSUE THREAD

**Issue by thomasbit** [PAYONE-GmbH/shopware-5#154]
We encounter a serious problem with duplicates in the s_order table that are created by the plugin.

This occurs under certain circumstances:
- The shop is under high load
- Many sessions are being created in a very short amount of time

The MoptShopNotification::indexAction is called asynchronously by the PayOne servers after a user has completed a payment process. (we see 2-3min delays in our logs).
If the shop is under high load,  the probability that the garbage collector has removed the user session increases. If this has happend - the MoptShopNotification service will create duplicate entries in the s_order database table.

This is due to the fact, that in the following code segment, the order is saved using the core Shopware method Payment::saveOrder, which in turn uses the session.

```php
        if (!$isOrderFinished) {
            $orderHash = md5(serialize($session['sOrderVariables']));
            $customParam = explode('|', $request->getParam('param'));

            if ($orderHash !== $customParam[2]) {
                $this->logger->error("Order for {$transactionId} corrupted - order hash mismatch", ['transactionId' => $transactionId]);
                $orderIsCorrupted = true;
                $paymentStatus = 21;
                $orderNumber = $this->saveOrder($transactionId, $request->getParam('reference'), $paymentStatus);
            } else {
                $this->logger->debug("Save order for {$transactionId} - order hash validation succeeded.", ['transactionId' => $transactionId]);
                $orderNumber = $this->saveOrder($transactionId, $request->getParam('reference'));
            }

            $order = $this->loadOrderByOrderNumber($orderNumber);
        }
```

Payment:.saveOrder

```php
        $sql = '
            SELECT ordernumber FROM s_order
            WHERE transactionID=? AND temporaryID=?
            AND status!=-1 AND userID=?
        ';
        $orderNumber = Shopware()->Db()->fetchOne($sql, [
                $transactionId,
                $paymentUniqueId,
                Shopware()->Session()->sUserId,
            ]);
```

This is a serious issue, because the duplicate orders lead to many failed requests during the further processing of orders (capturing, refunding..)
Furthermore the above code to check the integrity of the order by using an order hash will always fail, if the user session could not be properly restored.

Our proposal would be
- to eliminate the usage of the Shopware function to save the order and instead use a custom implementation to update the required fields.
- Properly handle the case, if a user session could not be restored

We gladly help with more input if needed.

Greetings
Thomas

**Comment by tpierschel** [comment]
Had the same issue twice.

**Comment by T-Kuchel** [comment]
Hello @tpierschel ,

we will investigate on this issue, and come back to you if we have any feedback or solutions.

Regards
Timo
