### ISSUE TITLE
Undefined Variables

### ISSUE THREAD

**Issue by fjbender** [PAYONE-GmbH/shopware-5#16]
We have the following undefined variables in the code:

* shopware/engine/Shopware/Plugins/Default/Frontend/MoptPaymentPayone/Controllers/Backend/FcPayone.php ll. 128-129 $data, $params
* shopware/engine/Shopware/Plugins/Default/Frontend/MoptPaymentPayone/Components/Classes/PayoneHelper.php l. 174 $userId
* shopware/engine/Shopware/Plugins/Default/Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php ll.178, 180 $alreadCapturedAmount
* shopware/engine/Shopware/Plugins/Default/Frontend/MoptPaymentPayone/Subscribers/AddressCheck.php ll. 219-221 $session
* shopware/engine/Shopware/Plugins/Default/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentPayone.php l. 261 $moptPaypalEcsWorkerId
* shopware/engine/Shopware/Plugins/Default/Frontend/MoptPaymentPayone/Subscribers/AddressCheck.php ll. 299-301 $session
* shopware/engine/Shopware/Plugins/Default/Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php l. 407 $payment
* shopware/engine/Shopware/Plugins/Default/Frontend/MoptPaymentPayone/Controllers/Backend/FcPayone.php ll. 626, 647, 669, 690  $myForm; l. 776 $params, l. 777 $data, l. 1000 $breadcrump
* shopware/engine/Shopware/Plugins/Default/Frontend/MoptPaymentPayone/Subscribers/AddressCheck.php l. 633 $userId

They need to either be defined or removed from the code.

**Comment by Fatchip-Support** [comment]
This issue should be fixed now
The unused $session variables in Addresscheck.php are false positives and can be ignored.
