### ISSUE TITLE
Capture Order fails with Exception: Entity of type 'Shopware\Models\Tax\Tax' for IDs id(0) was not found

### ISSUE THREAD

**Issue by NilsEvers** [PAYONE-GmbH/shopware-5#167]
There is an issue when capturing orders in the shopware backend. The issue arises for orders which contain a position with `taxID 0` assigned. This may be the case when the order contains a voucher. Capturing an order will result in the following Exception: `Entity of type 'Shopware\Models\Tax\Tax' for IDs id(0) was not found`

The responsible code is found in [Mopt_Payone_ParamBuild::getInvoicingFromOrder() - Line 1346](https://github.com/PAYONE-GmbH/shopware-5/blob/f5646fde1f24465b0ff51e589251d1e035d10f40/Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php#L1346)

There is another issue related to the very same code: There are some orders where the capture fails with `[Symfony\Component\Debug\Exception\FatalThrowableError]  Call to a member function getTax() on null`. You should probably include a check for null before calling `getTax()`.

**Comment by fjbender** [comment]
Thanks for the detailed analysis - we'll take a look and fix it.

**Comment by NilsEvers** [comment]
Thank you for fixing this issue. Is there a schedule for the next release yet? I also noticed that the last release v3.8.0 isn't available through the Shopware store.
