### ISSUE TITLE
Payment-Status-Mapping for appointed is ignored

### ISSUE THREAD

**Issue by NilsEvers** [PAYONE-GmbH/shopware-5#171]
The payment-status-mapping is ignored. Instead of using the value defined in the config, the hard-coded value 18 (reserved) is used.

The problematic code is in the [MoptShopNotification-Controller on line 173](https://github.com/PAYONE-GmbH/shopware-5/blob/137b66655b5da8abca323063fe8597c133b7ec09/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptShopNotification.php#L173). 

This is a severe problem for us because a lot of our orders rely on the payment-status and won't be processed otherwise.

**Comment by NilsEvers** [comment]
Is there any news regarding this issue? As I pointed out this is a severe bug for our client.

I also like to point out another issue, which may also be related to the same code-block. Some orders are set to the state 119, which is amazon_delayed, even though the payment method is not Amazon Pay. I am not sure if the failed cause is set to a wrong value, when you process the order or if you misinterpret the value and take the wrong actions in the code I mentioned above.

**Comment by fjbender** [comment]
Sorry, I was on leave and couldn't get back to your issue until today.

I realize that some merchants rely on the appointed status mapping to something specific while other merchants rely on us mapping it statically to reserved. We should find a better approach to this without breaking the default mapping many merchants are accustomed to.

The second issue is somewhat interesting. Which payment methods are affected? I'm guessing PayPal?
As I look at the code, I realize it is somewhat generic, but still mapping it to a payment method specific code - this should be improved. We should check whether the order is an actual Amazon Pay order before mapping it to state 119.

**Comment by NilsEvers** [comment]
Yes, all the orders that got mapped to state 119 have the payment method PayPal.

**Comment by fjbender** [comment]
I suppose, as the pending status with PayPal is only temporary, that the orders should change to "reserved" after a while. But still, we need to improve the amazon_pending status thing.

**Comment by NilsEvers** [comment]
It is actually the other way around. The orders are saved with status 17 and a few minutes later are updated to 119 via the Payone shop-notification. We have to change the status by hand or the orders won't get processed otherwise.

Our client's Shop has quite a large amount of orders per day. And those issues are a serious problem for us.

Is there a roadmap for when this will be fixed?

**Comment by fjbender** [comment]
Okay, that's weird, seems like the notifications are coming in the wrong order. Can you send me the merchant ID and one or two affected TXIDs per Mail to integrations@bspayone.com? Thanks!

We'll see if we can fix this on our side or need to issue a patch for the Shopware connector.

**Comment by fjbender** [comment]
@NilsEvers Can you confirm that #175 fixes the issue? It looked good in my tests.

**Comment by fjbender** [comment]
We have fixed this issue with #175
