### ISSUE TITLE
uninstall() does not clean enough

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#18]
Uninstalling the plugin does not remove all created entries from s_core_menu so it causes duplicate entries issues when trying to reinstall the plugin one more time.

**Comment by fjbender** [comment]
Apparently not fixed with #13

**Comment by Fatchip-Support** [comment]
Hi, i cannot confirm this.
I checked the database after uninstall; the entry is removed correctly.
I think this happend after a previously faulty uninstall run of the module.

**Comment by Fatchip-Support** [comment]
Nevertheless, i will add an extra check to the installation routine to prevent the creation of the menu item, if it already exists.
