### ISSUE TITLE
AmazonPay immer im Sandbox-Modus

### ISSUE THREAD

**Issue by MarcoBecker** [PAYONE-GmbH/shopware-5#183]
AmazonPay kann aktuell nicht im Live-Betrieb genutzt werden da, obwohl im Backend in den PayOne-Konfigurationen der Live-Modus ausgewählt ist, in allen Templates(bspw. ajax_cart_amazon.tpl) immer das Sandbox-JavaScript eingebunden wird:
`script async="async"
        src='https://static-eu.payments-amazon.com/OffAmazonPayments/de/sandbox/lpa/js/Widgets.js'>
</script`

Eine Abfrage nach Sandbox- oder Live-Modus gibt es hier nicht.

Shopware 5.4.1, PayOne Plugin 3.8.2

**Comment by fjbender** [comment]
Das ist definitiv ein Bug. Schauen wir uns an.

**Comment by MarcoBecker** [comment]
Funktioniert. Ich werde jetzt zur live-Seite von Amazon weitergeleitet
