### ISSUE TITLE
AmazonPay: Fatal error: Uncaught Error: Call to a member function getMaxTax() on null

### ISSUE THREAD

**Issue by MarcoBecker** [PAYONE-GmbH/shopware-5#184]
Nachdem Amazon über Shopware aufgerufen wurde, logge ich mich mit meinen Zugangsdaten ein. Anschließend muss ich bestätigen, dass meine Daten an den Shop übergeben werden. Stimme ich dem zu werde ich weitergeleitet und lande im Shop auf der Seite:
https://www.xyz.de/moptPaymentAmazon#access_token=...

mit der Fehlermeldung:

Fatal error: Uncaught Error: Call to a member function getMaxTax() on null in /home/derwedbm/www.cellavita.de/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentAmazon.php:673 Stack trace: #0 /home/derwedbm/www.cellavita.de/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentAmazon.php(98): Shopware_Controllers_Frontend_MoptPaymentAmazon->getTaxRates(Array) #1 /home/derwedbm/www.cellavita.de/engine/Library/Enlight/Controller/Action.php(193): Shopware_Controllers_Frontend_MoptPaymentAmazon->indexAction() #2 /home/derwedbm/www.cellavita.de/engine/Library/Enlight/Controller/Dispatcher/Default.php(549): Enlight_Controller_Action->dispatch('indexAction') #3 /home/derwedbm/www.cellavita.de/engine/Library/Enlight/Controller/Front.php(222): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp)) #4 /home/derwedbm/www.cellavita.de/engine/Shopware/Kernel.php(215 in /home/derwedbm/www.cellavita.de/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentAmazon.php on line 673

Shopware 5.4.1, PayOne Plugin 3.8.2

**Comment by fjbender** [comment]
Könnte auch ein Bug sein. Sind Voucher im Warenkorb?

**Comment by MarcoBecker** [comment]
Hi.
Voucher nicht aber ein kostenloses Prämienprodukt.

**Comment by fjbender** [comment]
Auch hier: #186 sollte das fixen, wir testen aktuell noch, aber dein Feedback hilft auch immer! :)

**Comment by MarcoBecker** [comment]
Der Fatal error ist weg. Funktioniert.

**Comment by fjbender** [comment]
Fixed with #186
