### ISSUE TITLE
AmazonPay: Keine Übertragung der Kundendaten in die Checkout Review-Seite

### ISSUE THREAD

**Issue by MarcoBecker** [PAYONE-GmbH/shopware-5#187]
Hallo.
Nachdem die Probleme mit dem Sandbox-Mode und dem Fatal error gefixt wurde, stehe ich nun vor dem nächsten Problem:
- Ich klicke im Shop auf den Amazon Pay Button
- Logge mich bei Amazon mit meinen Daten ein
- Werde wieder in den Shop zurück geleitet
- Der Container amazonContentWrapper hat außer zwei Sub-Divs keinen Inhalt. Normalerweise sollten hier die Adress- und Zahlungsdaten des Amazon Kontos stehen.
- Der Kaufen-Button ist ausgegraut und lässt sich nicht aktivieren.

**Comment by fjbender** [comment]
Ich glaube, das ist ein bekanntes Problem und auch bei uns im Test schon aufgefallen. Schmeißt die JS Console ein
`Uncaught TypeError: $ is not a function
    at window.onAmazonLoginReady (moptPaymentAmazon?access_token=Atza|[token]&token_type=bearer&expires_in=3600&scope=profile payments%3Awidget payments%3Ashipping_address payments%3Abilling_address:314)
    at Widgets.js:132
    at Widgets.js:132
    at Widgets.js:132
    at Widgets.js:132` ?

Ich vermute, dass wir da eine JS Race Condition haben, weil nicht berücksichtigt wurde, dass die Auslieferung von jQuery langsamer sein kann, als die Auslieferung der Widgets. Sollte sich aber mit dem `document.asyncReady()` Wrapper beheben lassen. Da sind wir grad dran.

**Comment by MarcoBecker** [comment]
Hi.
Genau diese Fehlermeldung bekomme ich in der Console auch angezeigt.

**Comment by MarcoBecker** [comment]
Hi. Seid ihr bei diesem Problem schon weiter gekommen?

**Comment by fjbender** [comment]
Moin! Das ist aktuell noch in der Entwicklung.
