### ISSUE TITLE
straight from the error log...

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#19]
[Tue Jun 28 15:57:38.284902 2016] [:error] [pid 6433] [client 10.6.219.2:44823] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Payone_Protocol_Logger_Log4php::setConfig() must be of the type array, null given, called in /var/www/XX.XX.XX.XXX.XX/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Payone/Builder.php on line 355 and defined in /var/www/XX.XX.XX.XXX.XX/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Payone/Protocol/Logger/Log4php.php:186\nStack trace:\n#0 /var/www/XX.XX.XX.XXX.XX/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Payone/Builder.php(355): Payone_Protocol_Logger_Log4php->setConfig(NULL)\n#1 /var/www/XX.XX.XX.XXX.XX/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Payone/Builder.php(288): Payone_Builder->buildServiceProtocol(Array, 'api')\n#2 /var/www/XX.XX.XX.XXX.XX/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Payone/Builder.php(161): Payone_Builder->bui in /var/www/XX.XX.XX.XXX.XX/htdocs/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Payone/Protocol/Logger/Log4php.php on line 186, referer: http://XX.XXX.XXX.XXX.de/checkout/cart

**Comment by fjbender** [comment]
Seems to be a PHP7 strictness issue.

**Comment by fjbender** [comment]
Should be fixed in 56a75db
