### ISSUE TITLE
payment methods overview > button duplicate payment methods > UX wrong

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#20]
Hi,

the button "duplicate payment method" is right from "save", should be left from "save" button because this is where you expect to click "forward" or "save" an action.

I always duplicate the payment methods when doing some changes to a method.

**Comment by Fatchip-Support** [comment]
This not an issue of the module but the standard shopware ux.
Please open this issue with Shopware directly.
https://github.com/shopware/shopware
