### ISSUE TITLE
amazon-pay: Errors beim Redirect zurück auf den Shop

### ISSUE THREAD

**Issue by MarcoBecker** [PAYONE-GmbH/shopware-5#207]
Hallo.

Wir haben nach wie vor Probleme mit amazon-pay. Aktuell bekommen wir in der Browser-Konsole die Error-Meldungen vom angehängten Screenshot angezeigt.
![amazon-pay-error](https://user-images.githubusercontent.com/886888/42802864-6f1fd696-89a4-11e8-8631-708a605af25d.png)

Beste Grüße
Marco

**Comment by fjbender** [comment]
Der 503er deutet auf ein serverseitiges Problem hin. Gibt es ein entsprechendes Exception Log in var/log?

**Comment by MarcoBecker** [comment]
Wenn ich von Amazon auf den Shop zurück geleitet werde, bekomme ich im core_production.log folgendes angezeigt:

[2018-07-17 10:59:26] core.CRITICAL: email: Bitte geben Sie eine gültige E-Mail-Adresse ein email: Bitte geben Sie eine gültige E-Mail-Adresse ein  [] {"uid":"0e1ad88"}
[2018-07-17 10:59:26] core.CRITICAL: email: Bitte geben Sie eine gültige E-Mail-Adresse ein email: Bitte geben Sie eine gültige E-Mail-Adresse ein  [] {"uid":"0e1ad88"}
[2018-07-17 10:59:26] core.ERROR: email: Bitte geben Sie eine gültige E-Mail-Adresse ein email: Bitte geben Sie eine gültige E-Mail-Adresse ein  [] {"uid":"0e1ad88"}

Aktualisiere ich die Checkout-Seite im Shop nochmal, wird das dunkle Overlay doppelt geladen, die Fehlermeldung ist weg und ich kann die Bestellung durchführen nachdem das Overlay ausgeblendet wurde.

**Comment by fjbender** [comment]
Ich würde gerne zunächst durch unseren Technical Support einmal prüfen lassen, ob an der API-Kommunikation alles glatt geht - bitte wende dich dazu einmal an tech.support@bspayone.com oder +49 431 25968-500.

Danke
Florian

**Comment by MarcoBecker** [comment]
Hi Florian.

Habe mich an den Tech-Support gewendet. Weiter gekommen sind wir hier aber leider nicht:

Sehr geehrter Herr Becker,
vielen Dank für Ihre Rückmeldung.
Das von Ihnen beschriebe Problem konnten wir nicht nachstellen. 
Da an der API-Kommunikation kein Fehler festgestellt werden kann würden wir ein Support Ticket für Sie anlegen und dieses durch unser Produkt Management bearbeiten lassen.
Da Sie aber schon auf GitHub mit einem Produktmanager von uns in Kontakt sind macht es vielleicht Sinn die Kommunikation auf diesem Weg fortzuführen.
Teilen Sie uns gerne mit wenn wir für Sie weiter tätig werden dürfen.
Bei Fragen stehen wir Ihnen gerne zur Verfügung.
Mit freundlichen Grüßen
Martin Krebs
Technical Support Engineer

Viele Grüße
Marco

**Comment by fjbender** [comment]
Ok, dann können wir das schon mal ausschließen. Kannst du mir die URL vom Shop mal an integrations@bspayone.com schicken? Dort sollte Amazo Pay im Testmodus auch aktiviert sein, damit ich schauen kann.

**Comment by hreinberger** [comment]
closing this due to non-activity. If this is still an issue, please re-open or create a new one.
