### ISSUE TITLE
cant save credentials in credit card config in backend 

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#21]
see summary

**Comment by fjbender** [comment]
Can't reproduce in SW 5.1.5 on PHP 5.6.4. PHP7 issue?

**Comment by Fatchip-Support** [comment]
One of the Options had an an empty value, but had to be set to either yes or no.
Now the form can be properly saved.

**Comment by fjbender** [comment]
I'm getting the following error in a PHP 7.0.4 environment:

`[Fri Jul 01 14:24:06.105574 2016] [:error] [pid 20327] [client 10.0.4.5:62753] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Shopware\\CustomModels\\MoptPayoneCreditcardConfig\\MoptPayoneCreditcardConfig::setShop() must be an instance of Shopware\\CustomModels\\MoptPayoneCreditcardConfig\\Shop, instance of Shopware\\Models\\Shop\\Shop given, called in /var/www/shops/sw-dev/engine/Shopware/Components/Model/ModelEntity.php on line 50 and defined in /var/www/shops/sw-dev/engine/Shopware/Plugins/Default/Frontend/MoptPaymentPayone/Models/MoptPayoneCreditcardConfig/MoptPayoneCreditcardConfig.php:596\nStack trace:\n#0 /var/www/shops/sw-dev/engine/Shopware/Components/Model/ModelEntity.php(50): Shopware\\CustomModels\\MoptPayoneCreditcardConfig\\MoptPayoneCreditcardConfig->setShop(Object(Shopware\\Models\\Shop\\Shop))\n#1 /var/www/shops/sw-dev/engine/Shopware/Controllers/Backend/Application.php(456): Shopware\\Components\\Model\\ModelEntity->fromArray(Array)\n#2 /var/www/shops/sw-dev/engine/Shopware/Plugins/Default/Frontend/MoptPaymentPayone/Controllers/Backend/MoptPayoneCreditcardConfig.php(84): Shopware_Controllers_Back in /var/www/shops/sw-dev/engine/Shopware/Plugins/Default/Frontend/MoptPaymentPayone/Models/MoptPayoneCreditcardConfig/MoptPayoneCreditcardConfig.php on line 596, referer: http://lamp03.pui.payone-office.de/shops/sw-dev/backend/`
