### ISSUE TITLE
Incomatibility with NETINVENTORS PrePaid Plugin

### ISSUE THREAD

**Issue by isd-maddin** [PAYONE-GmbH/shopware-5#213]
Hi,

we do get this fault if Payone 3.9.0 and NETINVENTORS PrePaid Plugin (v1.2.9) are installed: [Mon Jul 30 11:30:38.843718 2018] [fcgid:error] [pid 41732] mod_fcgid: process /var/www/web1/conf/php5/php-fcgi-starter(51238) exit(communication error), get unexpected signal 11

The customer cannot use the basket and cannot buy anything. We use Shopware 5.4.3.

Thanks for help!!

**Comment by fjbender** [comment]
The PrePaid Plugin is encrypted using IonCube, we can't help here. I'm sorry.

**Comment by tpierschel** [comment]
Hi, our Plugin for SW5.5.x isnt encrypted anymore.

**Comment by fjbender** [comment]
@tpierschel Great! :)
@isd-maddin Can you install the unencrypted plugin and provide a more detailed error message (i.e. stack trace etc.)?

**Comment by hreinberger** [comment]
closing this due to non-activity. If this is still an issue, please re-open or create a new one.
