### ISSUE TITLE
payone_service does not exist

### ISSUE THREAD

**Issue by freddydevio** [PAYONE-GmbH/shopware-5#219]
Hallo,

wir wollen die capture Funktion des payone_services nutzen der eigentlich im Plugin bereitgestellt wird. Allerdings bekommen wir die DI Container Fehlermeldung dass dieser Service nicht existiert. 
Aufgerufen wird das ganze normal über den Container "Shopware()->Container()->get('payone_serivce')".

Gibt es hier eine Lösung zu dem Problem? Ich vermute mal, dass die Klasse bzw. die Ressource einfach nicht korrekt initiiert wird.

**Comment by fjbender** [comment]
Wir haben den Service mit #131 als Service definiert. Er wird [hier](https://github.com/PAYONE-GmbH/shopware-5/pull/131/files#diff-296359e7d4b57d4b43eb454b21a5abe4) registriert. Nach der [Doku](https://developers.shopware.com/developers-guide/services/#registering-the-service) sollte der Service allerdings über die services.xml registriert werden.

Vielleicht brauchen wir vielleicht nur eine `Resources/services.xml` a la

```xml
<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <services>
        <service id="payone_service" class="Mopt_PayoneService" />
    </services>

</container>
```

**Comment by smartwebtools** [comment]
Aktuell wird das InitRessource Event registriert mit entsprechender Service Klasse als Return Wert. Das sollte meines Wissens auch so klappen.
Ich befürchte, dass das Problem eher ist, das die Klasse unter keinem eigenem Namespace ist und durch die Plugin Bootstrap in einem Class Autoload überhaupt erst geladen ist. Aber zu einem Zeitpunkt der Service Deklaration dieser Namespace gar nicht vorherrscht bzw. bekannt ist.

**Comment by fjbender** [comment]
Hast du einen konkreten Vorschlag? Ich weiß grade nicht so genau, was der Autoloader so braucht, um die Klasse zu finden. Ansonsten lasse ich gern mal einen Entwickler drauf schauen.

**Comment by shyim** [comment]
```xml
<service id="payone_service" class="Mopt_PayoneService" synthetic="true" />
```

Sollte das problem lösen

**Comment by smartwebtools** [comment]
> ```
> <service id="payone_service" class="Mopt_PayoneService" synthetic="true" />
> ```
> 
> Sollte das problem lösen

Hi @shyim , 
ich habe den Service  dann in meiner services.xml deklariert. Anschließend in meiner eigenen Klasse implementiert.
Allerdings bekomme ich dann den Fehler:
array (
  'error' => 'You have requested a synthetic service ("payone_service"). The DIC does not know how to construct this 
Ist das die falsche Stelle?

**Comment by rofthedeep** [comment]
@smartwebtools hast du dafür mittlerweile eine Lösung gefunden? Ich würde auch gerne darauf zugreifen, bekomme aber den gleichen Fehler.

**Comment by hreinberger** [comment]
Sollte das Thema noch aktuell sein gerne reopen.
