### ISSUE TITLE
Transaction status processing broken on PHP7

### ISSUE THREAD

**Issue by fjbender** [PAYONE-GmbH/shopware-5#22]
When push a transaction status to an instance running on PHP7 we receive the "error processing request" response from the MoptShopNotification controller at https://github.com/PAYONE-GmbH/shopware-5/blob/master/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptShopNotification.php#L81

Somehow the array mapping in the Transaction Service doesn't work, but I can't quite put my finger on it.

**Comment by Fatchip-Support** [comment]
Hi Florian,
i will check this today. All Testing had been done only locally.

**Comment by Fatchip-Support** [comment]
fixed in 19de09dff64441e6682254a8780fcf36ba52907d
