### ISSUE TITLE
Klarna: Fehler bei Bestellungen mit Einzelartikel und Bundle

### ISSUE THREAD

**Issue by mfritsche-dotsource** [PAYONE-GmbH/shopware-5#221]
Hallo,

im Zusammenhang mit Bundles kommt es mit der Payone Version 3.9.0 zu einem Fehler bei der Bezahlung über Klarna.

Folgendes Szenario:
Ein Kunde legt im Shop einen Einzelartikel mit der Artikelnummer SW0001 in den Warenkorb. Dann findet er ein Bundle, welches neben anderen Artikeln auch das soeben in den Warenkorb gelegte Produkt SW0001 enthält und legt auch dieses in den Warenkorb. Auf der Warenkorbseite wird nun der Artikel mit der Nummer SW0001 zwei Mal aufgeführt. Einmal als eigene Position außerhalb des Bundles und einmal innerhalb. Beide Male mit der identischen Artikelnummer. Geht der Kunde nun zur Kasse und wählt Klarna als Zahlart und möchte die Bestellung abschicken, kommt es zu einem Fehler auf der Seite von Payone. Im Log findet man dazu den Eintrag "Article list faulty or incomplete". Hierbei wurde die Bestellung nun abgelehnt, da die Artikelliste zwei Positionen mit identischer Artikelnummer beinhaltet, Payone aber eine eindeutige Nummer erwartet.

Ist dieses Verhalten seitens Klarna so vorgegeben, sodass hier eine Anpassung an dem Bundle Artikelhandling notwendig wird oder eventuell ein Fehler im Payone Plugin?

**Comment by hreinberger** [comment]
Hallo @mfritsche-dotsource 
Klarna lässt tatsächlich keine Artikel mit identischen Artikelnummern in unterschiedlichen Zeilen der Bestellung zu. Der Klarna-interne Fehler dafür lautet _9239 | notuniqueartnosoninvoice_ - wir mappen diesen auf unseren eigenen Fehler 1610.
Damit solche Bestellungen also durchgehen, müssten die Bestellzeilen so aufgebaut werden, dass Artikel mit identischer Artikelnummer auch nur ein Mal auftauchen, und sich dementsprechend die Menge anpasst.
