### ISSUE TITLE
credit card expiry check: month december not valid at any time?

### ISSUE THREAD

**Issue by kuschneider** [PAYONE-GmbH/shopware-5#227]
Is this correct? In the CheckCreditCardExpiry Action:

` $cardExpireNextMonth = strtotime("01-" . ($expireMonth +1) . "-20" ."$expireYear". " " ."23:59:59");`

A expireMonth of 12 + 1 will never return a valid timestamp, so showExpiryErrorMessage will be thrown. As long as I know all credit card test data are month 12 and actual year. Or did payone change this?

**Comment by fjbender** [comment]
Oh well, handling dates is difficult. However, we have a documented testcase where a month=12 credit card went through successfully. Nevertheless, this is a bug, we'll get it fixed. Thanks for the feedback!
