### ISSUE TITLE
Prepare plugin for composer installation

### ISSUE THREAD

**Issue by schliesser** [PAYONE-GmbH/shopware-5#229]
Can you please add support for composer-installers?
 
Here are some instructions from shopware how to prepare plugins: https://github.com/shopware/composer-project#prepare-plugins-for-composer-installation

And here are the instructions how to use these plugins:
https://developers.shopware.com/developers-guide/shopware-composer/#requiring-plugins

**Comment by fjbender** [comment]
This shouldn't be too much of a hassle, as I see it. I'll get to it after my vacation :)

**Comment by fjbender** [comment]
I now got around to testing this. However, our repo structure is not compatible. It's not easily reorganized, I'm afraid.
