### ISSUE TITLE
Replace-Hook wirft unter bestimmten Umständen eine Exception

### ISSUE THREAD

**Issue by MrMDeluxe** [PAYONE-GmbH/shopware-5#234]
Hallo,

der Replace-Hook von sGetOrderNumber() verursacht leider Probleme mit anderen Plugins, die diese Funktion im Backend Kontext benutzen.
Denn der Zugriff auf Shopware()->Session() funktioniert bekanntlich im Backend nicht.
Da die public Core Funktion sGetOrderNumber aber keinen Kontext vorschreibt, sollte der Hook hier die Verantwortung einer Prüfung für den richtigen Kontext haben.

Durch folgende Anpassung des Hooks wird hier der Session Zugriff auf den Frontend Kontext eingeschränkt:

```php
 public function onGetOrderNumber(\Enlight_Hook_HookArgs $args) {
        
        if(Shopware()->Container()->has('shop')){
            $session = Shopware()->Session();
            $moptRatepayOrdernum = $session->offsetGet('moptRatepayOrdernum');
        }
        if ($moptRatepayOrdernum) {
            return $moptRatepayOrdernum;
        } else {
            // standard behaviour
            $args->setReturn($args->getSubject()->executeParent(
                $args->getMethod(),
                $args->getArgs()
            ));
        }
    }
``` 

Wäre super, wenn Ihr den Fix übernehmen könntet.

**Comment by fjbender** [comment]
Klingt gut, wir prüfen das und übernehmen das dann wahrscheinlich.

**Comment by fjbender** [comment]
@MrMDeluxe Nur zur Vollständigkeit: Mit welchem Drittplugin können wir diesen Fehler reproduzieren?

**Comment by rmaassen** [comment]
Premium Gutschriften von Rhiem Intermedia GmbH. 

https://store.shopware.com/rhiem20364534336/premium-gutschriften.html

**Comment by rmaassen** [comment]
@fjbender wie ist denn hier der Status?

**Comment by fjbender** [comment]
Wir arbeiten noch dran, im Zuge der Analyse ist noch ein andere Bug mit Hooks aufgefallen, den wir gleich mit reparieren wollen.

**Comment by mediagraphik** [comment]
Wie ist der momentane Status hierzu?

**Comment by fjbender** [comment]
Sollte eigentlich mit #243 behoben worden sein - wir prüfen allerdings zur Zeit, ob das Problem nach #254 wieder auftritt.
