### ISSUE TITLE
PHP Fatal error: Uncaught Error: Call to a member function getArrayCopy() on null in MoptShopNotification.php:79

### ISSUE THREAD

**Issue by irwinbraganza** [PAYONE-GmbH/shopware-5#235]
This occurs for me just after the succesfull sofort payment and before the checkout finishAction (Thank you page) is called, here is the error:

`PHP Fatal error:  Uncaught Error: Call to a member function getArrayCopy() on null in /var/www/html/production/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptShopNotification.php:79`

_Originally posted by @irwinbraganza in https://github.com/PAYONE-GmbH/shopware-5/issues/37#issuecomment-428921737_

**Comment by hreinberger** [comment]
Hi @irwinbraganza 
we could sort out some of these cases where a faulty callback URL was configured in the merchant's PMI. Could you first contact our tech support with your merchant ID so they can check if the account is configured right? tech.support@bspayone.com 
thanks!

**Comment by irwinbraganza** [comment]
Thank you @hreinberger will confirm the configuration and get back to you.

**Comment by hreinberger** [comment]
closing this due to non-activity. If this is still an issue, please re-open or create a new one.
