### ISSUE TITLE
configuration widget is not able to save changes

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#24]
/backend/MoptConfigPayone/load/?f=m/Config|m/Signal|m/Payment|v/main/Window|v/main/Detail|store/Con…:263 Uncaught TypeError: Cannot read property 'data' of undefinedme.submit.failure @ /backend/MoptConfigPayone/load/?f=m/Config|m/Signal|m/Payment|v/main/Window|v/main/Detail|store/Con…:263Ext.apply.callback @ ext-all.js?201604081130:21Ext.define.afterAction @ ext-all.js?201604081130:21Ext.define.run @ ext-all.js?201604081130:21(anonymous function) @ ext-all.js?201604081130:21

me.submit.failure	@	/backend/MoptConfigPayone/load/?f=m/Config|m/Signal|m/Payment|v/main/Window|v/main/Detail|store/Con…:263
Ext.apply.callback	@	ext-all.js?201604081130:21
Ext.define.afterAction	@	ext-all.js?201604081130:21
Ext.define.run	@	ext-all.js?201604081130:21
(anonymous function)	@	ext-all.js?201604081130:21

**Comment by Fatchip-Support** [comment]
which configuration tab  did you try to save, when you got this error message?

**Comment by emtii** [comment]
Backend > Customers > Payment > Payone > Konfiguration > Tab Credit Assessment

Tried to change max basket value and save it. widget breaks

**Comment by Fatchip-Support** [comment]
fixed.
