### ISSUE TITLE
Automatische Korrektur in der  Adressüberprüfung verursacht Netto Bestellungen

### ISSUE THREAD

**Issue by MrMDeluxe** [PAYONE-GmbH/shopware-5#248]
Hallo,

das Payone Plugin verursacht immer netto Bestellungen, wenn die automatische Korrektur der Kundenadressen greift.

Im Subscriber FrontendPostDispatch wird in der Funktion onPostDispatchFrontend in der Zeile
304 die Variable  $view->sUserData mit dem Rückgabewert Shopware()->Modules()->Admin()->sGetUserData(); überschrieben.
Somit wird $view->sUserData['additional']['charge_vat'] entfernt und die Bestellung wird als netto angesehen.

Um dies zu fixen, sollte die Zeile 304 wie folgt geändert werden:
`$view->sUserData = array_replace_recursive($view->sUserData,
                                                                        Shopware()->Modules()->Admin()->sGetUserData());`

Bitte dringend fixen!

**Comment by T-Kuchel** [comment]
Hallo @MrMDeluxe ,

vielen Dank für den Hinweis!
Wir schauen uns das direkt an und melden uns, wenn wir Ergebnisse haben.

Beste Grüße aus Kiel
