### ISSUE TITLE
added payment restrictions in terms of max basket value bot not get recognized by "pre calc widget" of shopware"

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#25]
Added a max basket value of 1000 € to several payment methods in the backend then added 100 products with summarized value of 3000 € to the basket. I am still able to choose the payment method in the bottom left corner in shopwares pre shipping costs calculator.

**Comment by fjbender** [comment]
This is for the calculation of the theoretical shipping cost. It's not bindingly in any way. I'm not sure whether it makes sense to implement that feature.

**Comment by Fatchip-Support** [comment]
You can restrict paymentmeans by basket value and many other options with the stock shopware riskmanagement function, see
http://community.shopware.com/Riskmanagement_detail_859.html  (german documentation)

**Comment by Fatchip-Support** [comment]
The min and max basket value options are only used for triggering the payone internal risk- and address- check functions.

**Comment by emtii** [comment]
As the data are the same for both worlds, pre calc and real calc, its not really a "theoretical calc". Its the calc for real shipping costs so it makes sense to implement it there aswell. but as explained by fatchip the feature is not meant to do it that way so I use shopwares own feature.
