### ISSUE TITLE
Ordernumbers are overwritten with payment reference

### ISSUE THREAD

**Issue by hrombach** [PAYONE-GmbH/shopware-5#252]
Yesterday we updated a client's shop to v3.12.0 of the Plugin.
We noticed that the order number of all orders was being replaced by a string starting with 'mopt_' (what I would assume is a payment reference) until we enabled the option to use the shopware order number as payment reference.

In PR #245 I noticed this line: https://github.com/PAYONE-GmbH/shopware-5/pull/245/files#diff-cb93921fb53b442b3de357c8b8fb03e5R45

I assume this was only meant to change the order number under specific circumstances originally, but now it is always overwritten by the payment reference, which by default is the aforementioned string.

This is very unfortunate because it disrupts the order history and all customers get a cryptic string in their confirmation email.

**Comment by hreinberger** [comment]
Hi @hrombach 
thanks for pointing this out! We recently got aware of this and are working on a solution. For the time being I flagged the release as pre-production and pointed this out in the description. We're also working on rolling back to the last version in the shopware store.

**Comment by hreinberger** [comment]
It took a while, but we have a solution in #254 - though due to the holiday we'll release this in 2019. The PR is tested, so if you need a quick solution this should be relatively safe to integrate.
