### ISSUE TITLE
max basket value does not get recognized, still able to choose a invalid payment method

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#26]
Added a value of 1000 € to max basket value for several payment methods in the backend config Payments > Payone > Konfiguration

Added 100 items to the basket with summarized value of 3000 €.

I am still able to choose all payment methods.

**Comment by Fatchip-Support** [comment]
You can restrict paymentmeans by basket value and many other options with the stock shopware riskmanagement function, see
http://community.shopware.com/Riskmanagement_detail_859.html (german documentation)

The min and max  basket value options are only used for triggering the payone internal risk- and address- check functions.

**Comment by emtii** [comment]
ok - i know the risk management but someone of payone told me to use those fields in your config.

fine for me - closed
