### ISSUE TITLE
cant open backend widget

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#27]
Trying to open Customers > Payment Payone > Konfiguration

404

Ext.define('Shopware.apps.Index', {
extend:'Enlight.app.SubApplication',
bulkLoad: true,
loadPath: '/backend/Index/load',
controllers:[
'Main',
'Widgets',
'ErrorReporter',
'ThemeCacheWarmUp'
],
requires: [
'Shopware.container.Viewport'
],
views: [
'Main',
'Menu',
'Footer',
'Search',
'widgets.Window',
'widgets.Sales',
'widgets.Upload',
'widgets.Visitors',
'widgets.Orders',
'widgets.Notice',
'widgets.Merchant',
'widgets.News',
'widgets.Base',
'merchant.Window',
'themeCache.ThemeCacheWarmUp'
],
models: [
'Widget',
'WidgetSettings',
'Turnover',
'Batch',
'Customers',
'Visitors',
'Orders',
'News',
'Merchant',
'MerchantMail',
'ThemeCacheWarmUp'
],
stores: [
'Widget',
'WidgetSettings',
'ThemeCacheWarmUp'
]
});
Ext.define('Shopware.apps.Index.bestitTbOneWidget.model.State', {
extend: 'Ext.data.Model',
fields: [
'name',
'state'
]
});//
Ext.define('Shopware.apps.Index.bestitTbOneWidget.store.State', {
extend: 'Ext.data.Store',
model: 'Shopware.apps.Index.bestitTbOneWidget.model.State',
remoteSort: true,
pageSize: 25,
autoLoad: true,
proxy: {
type: 'ajax',
url: '/backend/BestitTbOneWidget/getStates',
reader: {
type: 'json',
root: 'data',
totalProperty: 'total'
}
}
});
Ext.define('Shopware.apps.Index.bestitTbOneWidget.view.Main', {
extend: 'Shopware.apps.Index.view.widgets.Base',
alias: 'widget.bestit-tb-one',
resizable: {
handles: 's'
},
minHeight: 350,
maxHeight: 600,
initComponent: function() {
var me = this;
me.stateStore = Ext.create('Shopware.apps.Index.bestitTbOneWidget.store.State').load();
me.tools = [
{
itemId: 'refresh',
type: 'refresh',
scope: me,
handler: me.refreshView
}
];
me.items = [
me.createStateGrid()
];
me.callParent(arguments);
},
createStateGrid: function() {
var me = this;
return Ext.create('Ext.grid.Panel', {
border: 0,
store: me.stateStore,
columns: me.createColumns()
});
},
createColumns: function() {
return [{
dataIndex: 'name',
header: 'Bezeichnung',
xtype: 'gridcolumn',
flex: 1
}, {
dataIndex: 'state',
header: 'Status',
xtype: 'gridcolumn'
}
]
},
refreshView: function() {
var me = this;
if(!me.stateStore) {
return;
}
me.stateStore.reload();
},
openTradeByte: function() {
openNewModule('Shopware.apps.BestitTbOne', {
action: 'list',
params: { }
});
}
});//
Ext.define('Shopware.apps.Index.bestitBvbCoreWidget.model.State', {
extend: 'Ext.data.Model',
fields: [
'name',
'state',
'module'
]
});//
Ext.define('Shopware.apps.Index.bestitBvbCoreWidget.store.State', {
extend: 'Ext.data.Store',
model: 'Shopware.apps.Index.bestitBvbCoreWidget.model.State',
remoteSort: true,
pageSize: 25,
autoLoad: true,
proxy: {
type: 'ajax',
url: '/backend/BestitBvbCoreWidget/getStates',
reader: {
type: 'json',
root: 'data',
totalProperty: 'total'
}
}
});
Ext.define('Shopware.apps.Index.bestitBvbCoreWidget.view.Main', {
extend: 'Shopware.apps.Index.view.widgets.Base',
alias: 'widget.bestit-bvbcore',
resizable: {
handles: 's'
},
minHeight: 125,
maxHeight: 300,
initComponent: function() {
var me = this;
me.stateStore = Ext.create('Shopware.apps.Index.bestitBvbCoreWidget.store.State').load();
me.tools = [{
type: 'refresh',
scope: me,
handler: me.refreshView
}];
me.items = [
me.createStateGrid()
];
me.callParent(arguments);
},
createStateGrid: function() {
var me = this;
return Ext.create('Ext.grid.Panel', {
border: 0,
store: me.stateStore,
columns: me.createColumns(),
});
},
createColumns: function() {
return [{
dataIndex: 'name',
header: 'Modul',
xtype: 'gridcolumn',
flex: 1
}, {
dataIndex: 'state',
header: 'Status',
xtype: 'gridcolumn',
flex: 1
}, {
xtype: 'actioncolumn',
width: 50,
items: [{
iconCls:'sprite-ui-scroll-pane-list',
tooltip: 'Log öffnen',
handler: function(view, rowIndex, colIndex, item, event, record) {
openNewModule('Shopware.apps.BestitBvbCore', {
params: {
filter: record.get('module')
}
});
}
}]}
]
},
refreshView: function() {
var me = this;
if(!me.stateStore) {
return;
}
me.stateStore.reload();
}
});//

**Comment by fjbender** [comment]
Can't reproduce on a fresh SW 5.2.1 with current Payone from git and PHP 7.0.4. What setup exactly are you using?

**Comment by emtii** [comment]
activate http cache

Request URL:http://admin.dev.b2c.bvb.sportsandbytes.de/backend/MoptConfigPayone?file=app&no-cache=1467902443+2+1
Request Method:GET
Status Code:404 Not Found (from cache)

**Comment by fjbender** [comment]
Still can't reproduce locally.

@Fatchip-Support can you take a look?

**Comment by Fatchip-Support** [comment]
The PAYONE Plugin was installed but not activated.
After activating everything seems fine now.

**Comment by fjbender** [comment]
Thanks.
