### ISSUE TITLE
Js Fehler bei Wechsel zwischen Kreditkarten

### ISSUE THREAD

**Issue by rofthedeep** [PAYONE-GmbH/shopware-5#275]
Hallo zusammen,

im Frontend wird beim Wechsel der Kreditkarte immer ein JS Error geworfen:

> Uncaught TypeError: Cannot read property 'contentWindow' of undefined

![Bildschirmfoto 2019-03-18 um 10 42 56](https://user-images.githubusercontent.com/2420176/54521261-da56e680-496a-11e9-9fa3-d1184839e399.png)

Der Fehler wird wohl in der payone_hosted_min.js Datei geworfen, auf die man hier keinen Einfluss hat.

**Comment by fjbender** [comment]
Moin,

ich kann das hier auf einem Testsystem nicht reproduzieren - vielleicht liegt's an einer Einstellung in der "Hosted iFrame" Konfiguration im Plugin, aus der Konfiguration wird dann ein JS-Objekt erzeugt, was der payone_hosted_min.js übergeben wird und dort Fehler erzeugen kann (was eigentlich nicht vorkommen sollte). 

Eine un-minified Version des von uns gehosteten JS findest du hier: https://secure.pay1.de/client-api/js/v1/payone_hosted.js. Vielleicht hilft das, den Fehler einzugrenzen?

**Comment by MJPese** [comment]
In unserem Shop tritt das Problem auch auf, ich kann es aktuell aber auch nicht wirklich eingrenzen. Auf framily.de ein Buch konfigurieren und versuchen, mit Kreditkarte zu bezahlen. Ich habe bereits testweise alle Anpassungen in der iframe-Konfiguration entfernt, aber ohne Erfolg

**Comment by FramilyTeam** [comment]
Hi @rofthedeep,

hat sich bei dir in der Zwischenzeit etwas ergeben?

**Comment by FramilyTeam** [comment]
Moin @fjbender,

hat Payone sich weiter mit diesem Thema beschäftigt?

**Comment by hreinberger** [comment]
Hi @FramilyTeam 
der Fehler ist für uns schwierig einzugrenzen, weil wir ihn auch mit mehreren Konfigurationen bisher nicht nachvollziehen konnten. Das Thema könnte also mit einer individuellen Serverkonfiguration oder Customizing im Shop zusammenhängen. Bitte wendet euch einmal an unseren tech support (falls nicht schon geschehen). Die Kollegen können eure individuelle Konfig anschauen und dann ggf. weitere Schritte einleiten.

**Comment by FramilyTeam** [comment]
Hi @hreinberger,

vielen Dank für die schnelle Antwort. Die von dir vorgeschlagenen Schritte haben wir zwischenzeitlich schon hinter uns lassen können. Selbst in den Standardeinstellungen sind Zahlungen per Kreditkarte nicht möglich. 

Wir befinden uns mitten im Ostergeschäft und benötigen dringend eine Lösung.

**Comment by rofthedeep** [comment]
@FramilyTeam in meiner lokalen Testumgebung tritt der Fehler weiterhin auf. Auf unserer Abnahmeumgebung jedoch nicht ... 
Wird in irgend einer Form ein Request von Payone an die Umgebung geschickt und kann das evtl. nicht aufgelöst werden?

**Comment by fjbender** [comment]
Hi @FramilyTeam, wenn's weiter pressiert, meldet euch bitte noch einmal beim Technical Support und wir vernetzen euch direkt mit den Entwicklern des Plugins, dann schauen die sich das direkt in eurem System an (Disclaimer: Das ist ne Leistung, die die direkt mit euch abrechnen würden, außer es ist ein Bug bei uns im Modul).
