### ISSUE TITLE
wrong customer ip with loadbalancer setup

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#29]
Hi,
currently we face the issue that in a setup with loadbalancer the plugin always submit the ip of the loadbalancer to payone instead of the customer ip.

Could you please have a look into that one? Thank you.

**Comment by fjbender** [comment]
@Fatchip-Support: IP is apparently set in \Mopt_PayoneParamBuilder::getPersonalData and grabbed from $_SERVER superglobal. Probably, a patch is needed to grab it from some kind of X-Forwarded-For header, if present. 

@emtii: Does your loadbalacer setup provide the actual customer's IP in any header fields?

**Comment by Fatchip-Support** [comment]
Hi,
i just added the necessary check, so that whenever the X-Forwarded-For Header is found it will be preferred over the REMOTE_ADDR Header.

**Comment by emtii** [comment]
ok thank you, payolution has to check this now

**Comment by emtii** [comment]
feedback is was fixed, so i close this one for now.
