### ISSUE TITLE
Kürzung Produktname nicht multi-byte safe

### ISSUE THREAD

**Issue by KevinHansenAgire** [PAYONE-GmbH/shopware-5#308]
Bei der Übermittlung des Produktnamens an Payone (create order) wird der Name auf 100 Zeichen gekürzt. Diese Kürzung erfolgt nicht multi-byte safe, sodass z.B. ein "ß" einen Fehler mit nicht erlaubten Steuerzeichen bei Payone verursacht. Der Kunde wird auf die Fehlerseite weitergeleitet und der Abschluss der Bestellung ist nicht möglich.

Verursacher scheint die Datei \shopware-5-master\Frontend\MoptPaymentPayone\Components\Classes\PayoneParamBuilder.php zu sein. Hier müsste

`$params['de'] = substr($article['articlename'], 0, 100); // description`

zu

`$params['de'] = mb_substr($article['articlename'], 0, 100); // description`

korrigiert werden.

**Comment by fjbender** [comment]
Danke für den Hinweis, ich habe einen entsprechenden PR erstellt.
