### ISSUE TITLE
implement field error handling shopware wise

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#31]
fields in template do not contain any type in error handling like shopware provides for all their fields. this should be implemented by default.

**Comment by fjbender** [comment]
I'll talke a look into that.

**Comment by fjbender** [comment]
I can't exactly see what you mean. For instance on the payment page templates, we validate all input fields (with exception of the credit card fields) on formal correctness:

```html
<input name="moptPaymentData[mopt_payone__payolution_debitnote_iban]" type="text" id="mopt_payone__payolution_debitnote_iban" required="required" aria-required="true" placeholder="IBAN*" value="" data-moptibanerrormessage="Dieses Feld darf nur Großbuchstaben und Ziffern enthalten" class="payment--field is--required moptPayoneIbanBic">
```

See example screenshot:

![input_validation_sepa](https://cloud.githubusercontent.com/assets/7370694/17805490/0dcd884e-6600-11e6-8dac-9a97f48f22bf.png)

Or did I completely misunderstand you?

**Comment by emtii** [comment]
No its fine for debit. but for creditcard there is nearly nothing. And sometimes there are really awful javascript popup windows.

Customer tried to add letters for credit card number instead of numbers, this is something what could get improved.

**Comment by fjbender** [comment]
I see what you mean. We're working on allowing the placeholder attribute in credit card fields, this feature will be available soon. 

To get rid of the error JavaScript alerts we do provide the feature to write the error message in a div field.

**Comment by fjbender** [comment]
Placeholders are available in CC config options now.
