### ISSUE TITLE
JavaScript Fehler mit IE11 bei Auswahl für eine Kreditkartenzahlung

### ISSUE THREAD

**Issue by annonyme** [PAYONE-GmbH/shopware-5#312]
Hallo,
einem Kunden mit IE11 fiel der Fehler auf, dass Kreditkarten-Informationen nicht ausgewertet werden, also keine Validierung oder Übernahme stattfindet. Er wird einfach weiter geleitet und behält die vorher schon genutzte Zahlungsart.
Ich konnte mit IE11 unter Win7 den Fehler "Object doesn't support property or method 'moptPayoneIbanBicValidator'" reproduzieren.

![VirtualBox_IE11 - Win7_25_07_2019_09_40_27](https://user-images.githubusercontent.com/28100023/61856048-9ef09980-aec1-11e9-9ba6-f8ea4557f773.png)

Eine Einschätzung und vielleicht Lösung des Problems wäre toll.

Hannes Pries
für notebookswieneu.de

**Comment by hreinberger** [comment]
Hi @annonyme
ich kann das leider noch nicht wirklich nachvollziehen. Auf Win10 mit dem IE11 scheint da alles richtig zu laufen. Wie kann ich das Problem reproduzieren?

**Comment by annonyme** [comment]
Hallo,
ich kann es auch auf dem IE11 mit Win10 reproduzieren. Ich gehe dabei so vor:

- Artikel in den Warenkorb legen
- zum Checkout gehen über den Warenkorb
- Einloggen
- Im Checkout die Zahlungsart ändern
- Da Kreditkarte auswählen
- Irgend einen Scheißt eingeben und auf "weiter" klicken

Dann lange ich wieder mit der urspünglichen Zahlungsart im Checkout-Confirm.
[pw5x7CH1CW.zip](https://github.com/PAYONE-GmbH/shopware-5/files/3445727/pw5x7CH1CW.zip)

Ich hab es einmal als Video (in der ZIP-Datei) angehängt, wie es sich mit Win10 + IE11 (11.590.17134.0) bei uns verhält.

**Comment by hreinberger** [comment]
Echt seltsam. Ich bekomme es auch mit diversen Varianten von Einloggen vor/nach Warenkorb und beliebigen ausgewählten Zahlungsarten nicht reproduziert. (auf SW 5.5.8 mit Plugin Version 3.13.0, Win 10 1803 und IE11 11.885.17134.0)
Bitte wende dich einmal an die Kollegen vom Tech Support (tech.support@bspayone.com) - die würden sich einmal die Konfig des Shops anschauen und zur Not den Prozess für individuellere Fehlerbehebung anstoßen.

**Comment by annonyme** [comment]
Ich werde erst einmal anstoßen von 5.5.7 auf eine aktuellere Version zu kommen. Sollte das nicht helfen, werden wir uns dann den Tech-Support wenden.

Danke für die Hilfe.

**Comment by hreinberger** [comment]
geschlossen wegen Inaktivität. Wenn das Thema noch besteht, melde dich gerne nochmal!
