### ISSUE TITLE
onUpdateAddress überschreibt Adressvalidierung

### ISSUE THREAD

**Issue by rofthedeep** [PAYONE-GmbH/shopware-5#324]
In der Klasse "AddressCheck" wird auf "Shopware_Controllers_Frontend_Address::ajaxSaveAction::after" ein Hook onUpdateAddress aufgerufen.

![Bildschirmfoto 2019-10-17 um 12 29 22](https://user-images.githubusercontent.com/2420176/67001376-dc884b80-f0d9-11e9-81a6-942213cee018.png)

Dieser Hook führt leider dazu, dass invalide Adressen abgespeichert werden.

Wir haben im System zusätzliche Validatoren der Adresse. Umgesetzt wie hier beschrieben:
https://developers.shopware.com/developers-guide/address-management-guide/

Diese greifen an allen anderen Stellen korrekt, nur an dieser Stelle durch den Hook leider nicht.

In unserem Fall validieren wir die Straße darauf, ob eine Nummer vorhanden ist. 

Mit einem entsprechendem Logging sieht man, dass der neue, falsche Wert durch den persist/flush in die Datenbank geschrieben wird.

<img width="696" alt="Bildschirmfoto 2019-10-17 um 12 49 15" src="https://user-images.githubusercontent.com/2420176/67002644-a4363c80-f0dc-11e9-8a6b-aa8c181ea310.png">

![Bildschirmfoto 2019-10-17 um 12 49 25](https://user-images.githubusercontent.com/2420176/67002645-a4363c80-f0dc-11e9-9eb6-cd081f561add.png)

![Bildschirmfoto 2019-10-17 um 12 49 39](https://user-images.githubusercontent.com/2420176/67002646-a4363c80-f0dc-11e9-82e5-0355c5df0998.png)

**Comment by fjbender** [comment]
Wir prüfen das mal. Ich befürchte aber, dass wir die ohnehin fragile Logik für die Adressverifikation und Boniprüfung dafür anfassen müssten. Das riecht nach recht viel Aufwand.

@Anton-Levitsky schau doch hier mal drauf (irgendwie kann ich dich nicht assignen)

**Comment by rofthedeep** [comment]
Alles klar, danke! Eine erste Möglichkeit wäre evtl. auch schon, den Code nur auszuführen wenn die Adressvalidierung / Bonitätsprüfung aktiviert ist. Dann kann der Fehler zumindest schon mal nur noch für die Personen auftreten, bei denen dieser Teil aktiv ist.

**Comment by fjbender** [comment]
#354 sollte das Problem nun endlich fixen. Für uns sieht das okay aus. Magst du auch noch mal schauen?
