### ISSUE TITLE
Problem with SSL-check in loadbalanced environment

### ISSUE THREAD

**Issue by SirUrban** [PAYONE-GmbH/shopware-5#333]
Hi,

there are two templates with an if-clause checking if the request is ssl encrypted:
* Frontend/MoptPaymentPayone/Views/frontend/checkout/ajax_cart_amazon.tpl
* Frontend/MoptPaymentPayone/Views/frontend/checkout/mopt_cart_amazon.tpl

This is done by checking the `$smarty.server.REQUEST_SCHEME` variable.
It does not work in setups where you have several app-servers behind a loadbalancer cause quite often the ssl connection is terminated in the loadbalancer and the connection between LB and app-servers is not ssl-encrypted.
To tell the app-servers that the external connection is encrypted usually the LB (nginx) sends some header information which can be used to force apache to fill some server variables correctly, like:

```
$_SERVER['HTTPS'] = 'on'
$_SERVER['HTTP_X_FORWARDED_PROTO'] = 'https'
$_SERVER['HTTP_HTTPS'] = 'on'

```
Unfortunately it seems not to be possible to force the $_SERVER['REQUEST_SCHEME'] variable of apache. At least I did not found a way to do this. So one of our clients with shopware-5 faces problems due to this issue.
Is there any solution for this?

From my point of view it would be a good idea to change the checks in the above named templates to something like this:

`{if $smarty.server.REQUEST_SCHEME === 'https' || $smarty.server.HTTPS === 'on' || $smarty.server.HTTP_HTTPS === 'on' || $smarty.server.HTTP_X_FORWARDED_PROTO === 'https'}`

What do you think?

Cheers,
Andy, ScaleCommerce GmbH

**Comment by Bugfighter** [comment]
Good suggestion in my point of view!

**Comment by hreinberger** [comment]
Thanks for the in-depth suggestion! Did you already solve this topic for your customer? If so, feel free to add a pull request. If not we'll fix this on our own, but will get back to you for further testing. Our internal testing stack doesn't use any load balancing setups, so it will be difficult for us to test internally.

**Comment by SirUrban** [comment]
The customer ist just testing it. I will wait for feedback and will add a pull-request soon.
