### ISSUE TITLE
Missung function moptShowGeneralIFrameError 

### ISSUE THREAD

**Issue by RQqrwTfK3uV5** [PAYONE-GmbH/shopware-5#336]
When creditcard payment uses the hosted iFrame solution and nothing else then the Credit card type is selected, after the submit a javascript error due to en undefined function is thrown:

Uncaught ReferenceError: moptShowGeneralIFrameError is not defined

See: engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Views/frontend/_resources/javascript/mopt_payment.js:545

Tested with Shopware 5.5.9 and Plugin Version 4.0.1

**Comment by hreinberger** [comment]
Hi, this should have been fixed by #321 which will ship in the next release. Can you try out the current master and confirm?

**Comment by RQqrwTfK3uV5** [comment]
Sorry for the late response. 

Yes this fixes the issue.
