### ISSUE TITLE
Disable Amazon Payment / Amazon Payment Cookie?

### ISSUE THREAD

**Issue by elbsurfer** [PAYONE-GmbH/shopware-5#346]
Hello,
I am using Shopware 5.6.4 and the latest version of the PayOne Plugin. In the Cookie Consent Manager I do see this: https://drop.torben.me/Screen-Shot-2020-03-03-12-26-59.png

We do not use Amazon Payments neither have this payment method activated. How can I disable the cookie/the information in the cookie consent manager? When I look through the code, it seems to be hardcoded.

Is there a plan to only add the Amazon Payment Cookie Rule here in case Amazon Payment is actually used in the shop?

**Comment by T-Kuchel** [comment]
Hi @elbsurfer ,

thank you for this useful hint. We are always testing with all methods on. So this issue accidentally was not in the focus.

> Is there a plan to only add the Amazon Payment Cookie Rule here in case Amazon Payment is actually used in the shop?

There was no plan to do this, but yet > of course ;-)

Regards
Timo

**Comment by elbsurfer** [comment]
@T-Kuchel Thanks for your quick action. Do you know if you can include it in the next release and and approximate time when this will be released?

**Comment by T-Kuchel** [comment]
Hi @elbsurfer ,

our next regular shopware 5 plugin release is planned at the end of April.
I think we can assure that the fix for this issue will be included.

Regards
Timo

**Comment by T-Kuchel** [comment]
fixed with latest release
