### ISSUE TITLE
payment method debit -german-

### ISSUE THREAD

**Issue by emtii** [PAYONE-GmbH/shopware-5#35]
Bei Lastschriftzahlung gibt es folgenden Bug:
- Wenn ich Land, Kontoinhaber, Konto-Nr. und BLZ ausgefüllt habe kann ich nicht bestellen. D.h. ich MUSS einen IBAN angeben.

Gewünschte Lösung:
- Wenn Land, Kontoinhaber, Konto-Nr. und BLZ ausgefüllt sind, ist der Iban kein Pflichtfeld mehr!
- Wenn Land, Kontoinhaber und Iban gefüllt sind, sind die Felder Konto Nr und BLZ keine Pflichtfelder mehr.

**Comment by fjbender** [comment]
Definitiv ein Bug, wir gehen in die Umsetzung.

**Comment by emtii** [comment]
Ist dies irgendwo in den Releases mit drin gewesen?

**Comment by fjbender** [comment]
Ja, das ist umgesetzt.
