### ISSUE TITLE
submit basket in combination with premium items throw error

### ISSUE THREAD

**Issue by bragento** [PAYONE-GmbH/shopware-5#361]
hello,

we have a problem with premium goods or say free items.  Steps to reproduce:
1. use Paypal Sandbox Account.
2. in payone configuration activate "basket handover" to yes
3. configure free items in Shopware Backend Menu "Marketing > Premium Items"
4. try to submit order with free items

In our case basket looks like
![basket](https://user-images.githubusercontent.com/4529135/79633249-91bcbe80-8164-11ea-9486-f9abc6528a55.png)

The Payone_Api_Request_Authorization Object have these invoice items
![Bildschirmfoto 2020-04-18 um 10 57 56](https://user-images.githubusercontent.com/4529135/79633327-0263db00-8165-11ea-853d-c426449c112a.png)

After sending Payment Request to Payone the following error response is turning back.
![Bildschirmfoto 2020-04-18 um 11 12 05](https://user-images.githubusercontent.com/4529135/79633433-d09f4400-8165-11ea-8acc-9cadffcdb19f.png)

We are using Shopware 5.6.6 and Payone in Version 4.2.1. We had this problem also in payone version 4.1.0. 
At the moment we can only prevent this error if we do not send the shopping cart with "basket handover" set to "no".
  
best regards

**Comment by hreinberger** [comment]
Hi @bragento 
the PayPal Endpoint we're talking to is picky about cart items without prices. Having just one item with amount=0 in your cart will let paypal transactions fail. You can mitigate this by deactivating "Warenkorbübergabe" in your PAYONE Settings:

![grafik](https://user-images.githubusercontent.com/40197225/79720507-fb61d780-82e0-11ea-8999-9ba930de23f4.png)
If you use other payment methods that rely on cart items, make sure you select PayPal in the first dropdown to set this for PayPal only.

**Comment by bragento** [comment]
Hi @hreinberger you mean, your Implemation about "basket handover" is wrong? If this is not working why is there this option for paypal or no hint in documentation?

**Comment by hreinberger** [comment]
AFAIK PayPal is the only payment method in our portfolio that's this picky about items having an amount of 0. We're trying to accommodate as many possible configurations as possible. Having cart items show up in your PayPal checkout is a nice feature for many merchants, but if your individual configuration involves cart items with amount=0, you'll have to deactivate this. 

We could however make this more clear in our documentation - I'll update our docs page accordingly.
