### ISSUE TITLE
Paymentstatus is zero

### ISSUE THREAD

**Issue by christian-jbc** [PAYONE-GmbH/shopware-5#378]
When someone pays with Visa or Mastercard, the paymentstatus is set to "0" instead of "Komplett bezahlt" as set in the Payone Settings.

- Shopware 5.5.10
- PayOne 4.2.2

![zahlungsstatus](https://user-images.githubusercontent.com/66314750/86597599-40221400-bf9c-11ea-85db-3aa025e529e6.png)
![payone_kontrollzentrum](https://user-images.githubusercontent.com/66314750/86597595-3f897d80-bf9c-11ea-8adf-798f43117606.png)

**Comment by T-Kuchel** [comment]
Hi @christian-jbc ,

please get in contact with our technical support team(tech.support@payone.com). 
Maybe another configuration is colliding here. They could help you with your configuration export, which you don't want to expose here ;-)

Regards from Kiel
Timo
