### ISSUE TITLE
Falscher Subshop nach Rückleitung in den Shop von Paypal / Kreditkartenverifizierung

### ISSUE THREAD

**Issue by rofthedeep** [PAYONE-GmbH/shopware-5#385]
Hallo zusammen,

aktuell beobachte ich ein seltsames Verhalten nach Rückleitung in den Shop von PayPal / der Kreditkartenverifizierung. 

Der Fehler tritt auf, wenn ein **Subshop** verwendet wird.

Die Rückleitung erfolgt über folgende Controller Actions, jeweils auf die URL des Subshops:

1. \Shopware_Controllers_Frontend_MoptPaymentPayone::successAction (Shop ID passt - in unserem Fall die 3 des Subshops)
2. \Shopware_Controllers_Frontend_MoptPaymentPayone::finishOrderAction (Shop ID passt - in unserem Fall die 3 des Subshops)
3. \Shopware_Controllers_Frontend_Checkout::finishAction (Shop ID ändert sich in 1 - Shop ID passt somit nicht mehr)

Durch diesen Fehler werden die Bestellungen dem falschen Subshop zugewiesen, die "falsche" checkout/finish Seite geladen (Inhalt und Template des Hauptshops, nicht des Subshops) und auch das falsche Mailtemplate wird verwendet.

Hatte dieses Verhalten auch schon wer anderes?  

Nach dem Speichern des Bestellung scheint der Shop den Shopcontext zu verlieren. Macht man im Anschluss einen Reload der Seite, passt der Shopcontext wieder. Nur sind eben die Bestellungen noch korrupt und die falschen Mails wurden verschickt.

Die besten Grüße,
Tim

**Comment by hreinberger** [comment]
Hi @rofthedeep 
wir schauen uns das Thema gerade mal an und melden uns bei Neuigkeiten.

**Comment by rofthedeep** [comment]
@hreinberger Danke dir - melde dich gerne, falls ich noch weitere Infos liefern oder unterstützen kann ...

**Comment by markusmichalski-fc** [comment]
Hallo @rofthedeep,
wir haben uns das angesehen und konnten es in keiner unseren Umgebungen nachstellen.

Wir könnten uns das direkt auf Ihrem Server ansehen, aber würden hierfür einen Supportauftrag benötigen. Diesen finden Sie hier: https://www.fatchip.de/out/media/FC_Payone_Plugin_Supportauftrag_Formular.pdf

Mit freundlichen Grüßen

Markus Michalski
Leitung Support
Fatchip GmbH

**Comment by rofthedeep** [comment]
@markusmichalski-fc Danke! Ich kläre das mit dem Kunden ab und melde mich ggf.!

**Comment by hreinberger** [comment]
Ich mache hier mal zu wegen Inaktivität. Wenn das Problem noch besteht, meldet euch gerne nochmal.
