### ISSUE TITLE
ajaxGetPaySafeToken fails Payone Klarna Payments

### ISSUE THREAD

**Issue by floatingbits** [PAYONE-GmbH/shopware-5#387]
On the ShippingPayment-Action page, when I use Payone Klarna Payments method, after checking the agreement checkbox, a call to /MoptAjaxPayone/ajaxGetPaySafeToken is sent, but fails with the following error message: 

```
{"error":
  { "type":"Error",
    "message":"Call to a member function set() on null",
    "file":
"\/var\/www\/engine\/Shopware\/Plugins\/Community\/Frontend\/MoptPaymentPayone\/Controllers\/Frontend\/MoptAjaxPayone.php",
    "line":1371}
}
```

I think this line 
`$this->Response()->headers->set('content-type', 'application/json');`

must actually be 
`$this->Response()->setHeader('content-type', 'application/json', true);`

At least in my setup. 

What I don't understand is in what setup it doesn't fail, in other words, why it passed your QA and what it is in my setup that makes it fail. 

Shopware-Version: 5.3
PHP-Version: 7.0

**Comment by fjbender** [comment]
Thanks for the report. This is a known issue that only occurs in Shopware <5.6, as Shopware changed the behavior there. We are already working on a fix.

**Comment by fjbender** [comment]
#388 should fix this issue and will be moved to QA now
