### ISSUE TITLE
Give order attribute "mopt_payone_payolution_clearing_reference" a better name

### ISSUE THREAD

**Issue by fjbender** [PAYONE-GmbH/shopware-5#40]
When rebuilding the order attribute model for Shopware 5.3 we should rename the mopt_payone_payolution_clearing_reference attribute to reflect its actual use. The attribute is used for all kinds of clearing references, not only Payolution.

Same goes for mopt_payone_payolution_workorder_id, as other payment methods might need workorderid reference in the future.

**Comment by hreinberger** [comment]
Milestone reached yay! 🎉
