### ISSUE TITLE
Exception during payment in Shopware 5.6 and Payone 4.4

### ISSUE THREAD

**Issue by andydandy80** [PAYONE-GmbH/shopware-5#421]
Shopware: 5.6.9, Payone 4.4.0

We got an exception during payment by credit card. What could be the problem?
Our webserver is within an Proxy/Load Balancer Setup.

`moptPayone.ERROR: error processing request ["
#0 /var/www/html/xxx/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Payone/TransactionStatus/Service/HandleRequest.php(118): Payone_TransactionStatus_Validator_Ip->validateRequest(Object(Payone_TransactionStatus_Request))\n
#1 /var/www/html/xxx/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Payone/TransactionStatus/Service/HandleRequest.php(95): Payone_TransactionStatus_Service_HandleRequest->validateRequest(Object(Payone_TransactionStatus_Request))\n
#2 /var/www/html/xxx/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Payone/TransactionStatus/Service/HandleRequest.php(83): Payone_TransactionStatus_Service_HandleRequest->handle(Object(Payone_TransactionStatus_Request))\n
#3 /var/www/html/xxx/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptShopNotification.php(137): Payone_TransactionStatus_Service_HandleRequest->handleByPost()\n
#4 /var/www/html/xxx/engine/Library/Enlight/Controller/Action.php(192): Shopware_Controllers_Frontend_MoptShopNotification->indexAction()\n
#5 /var/www/html/xxx/engine/Library/Enlight/Controller/Dispatcher/Default.php(478): Enlight_Controller_Action->dispatch('indexAction')\n
#6 /var/www/html/xxx/engine/Library/Enlight/Controller/Front.php(228): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))\n
#7 /var/www/html/xxx/engine/Shopware/Kernel.php(188): Enlight_Controller_Front->dispatch()\n
#8 /var/www/html/xxx/vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(102): Shopware\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n
#9 /var/www/html/xxx/vendor/symfony/http-kernel/HttpCache/HttpCache.php(453): Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler::handle(Object(Shopware\\Kernel), Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n
#10 /var/www/html/xxx/engine/Shopware/Components/HttpCache/AppCache.php(261): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->forward(Object(Symfony\\Component\\HttpFoundation\\Request), true, NULL)\n
#11 /var/www/html/xxx/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Shopware\\Components\\HttpCache\\AppCache->forward(Object(Symfony\\Component\\HttpFoundation\\Request), true)\n
#12 /var/www/html/xxx/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), true)\n
#13 /var/www/html/xxx/engine/Shopware/Components/HttpCache/AppCache.php(143): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->invalidate(Object(Symfony\\Component\\HttpFoundation\\Request), true)\n
#14 /var/www/html/xxx/vendor/symfony/http-kernel/HttpCache/HttpCache.php(181): Shopware\\Components\\HttpCache\\AppCache->invalidate(Object(Symfony\\Component\\HttpFoundation\\Request), true)\n
#15 /var/www/html/xxx/engine/Shopware/Components/HttpCache/AppCache.php(113): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n
#16 /var/www/html/xxx/shopware.php(122): Shopware\\Components\\HttpCache\\AppCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n
#17 {main}
"] []
`

Best regards,
Andreas Bielmeier

**Comment by hreinberger** [comment]
Hi @andydandy80 

this seems to occur due to your specific load balancing setup. You could validate this by adding your load balancer's IP here: https://github.com/PAYONE-GmbH/shopware-5/blob/654c0de753c80001e1efc0ac4641d9b37cd6d9a1/Frontend/MoptPaymentPayone/Components/Classes/PayoneConfig.php#L19 

We also look out for specific forwarding headers like x-forwarded-for and the cloudflare variant of it:
https://github.com/PAYONE-GmbH/shopware-5/blob/654c0de753c80001e1efc0ac4641d9b37cd6d9a1/Frontend/MoptPaymentPayone/Components/Payone/TransactionStatus/Validator/Ip.php#L102 

So for a more permanent solution you could make your proxy/loadbalancer forward the remote IP of the transactionstatus messages in these headers.

**Comment by andydandy80** [comment]
Problem solved by entering this values in Shopware config.php:
`
...
'trustedProxies' => [
    'REMOTE_ADDR',
    '192.168.xx.xx', // our load balancer ip
    '127.0.0.1',
    '*'
],
...
`
