### ISSUE TITLE
Fehler bei Benutzung der recurringAction im Backend

### ISSUE THREAD

**Issue by JensPetersRhiem** [PAYONE-GmbH/shopware-5#43]
Hallo PAYONE Support,
ich habe noch einen Fehler in der Version 3.4.0_5908 auf Shopware 5.2.9 entdeckt. Es geht um wiederkehrende Zahlungen über das Backend, wie sie z.B. von AboCommerce genutzt werden.

Der Fehler stellt sich wie folgt dar:

Einer unserer Kunden benutzt das Plugin AboCommerce um monatlich Abonnement-Bestellungen im Backend zu erzeugen. Dabei wird die recurringAction des PAYONE-Plugins angesprochen. Beim Erstellen des Request an PAYONE werden die Request-Parameter durch die Klasse Mopt_PayoneParamBuilder erzeugt. Innerhalb dieser Klasse gibt es die Funktion getBasketItems, die die Warenkorbparameter für den Request an PAYONE zusammenstellen (pr, no, de, va, etc.). Bei der Berechnung des Parameters pr wird auf das Array-Element $article['netprice'] zugegriffen. Dieses Element existiert allerdings nur im Frontend, da es aus der Session bezogen wird. Somit wird der Preis für alle Positionen immer mit 0 berechnet. Dadurch dass die Summe der Positionen dann nicht mehr mit dem an PAYONE übermittelten Gesamtbetrag (amount) übereinstimmt, schlägt der Request an PAYONE immer fehl.

Danke,
Jens Peters

**Comment by fjbender** [comment]
@JensPetersRhiem kann ich soweit nachvollziehen. Was wäre die Alternative zu ``$article['netprice']``?

**Comment by JensPetersRhiem** [comment]
@fjbender Da bin ich mir auch nicht sicher. Wir hatten das Plugin auch schon in einer älteren Version auf Shopware 4 benutzt. Da hat es mit AboCommerce einwandfrei funktioniert.

**Comment by JensPetersRhiem** [comment]
Gibt es hier schon weitere Erkenntnisse? Wann können wir mit einer Lösung rechnen?

**Comment by fjbender** [comment]
Wir müssen wahrscheinlich die recurringAction entsprechend den Shopware 5 Standards neu bauen müssen. Das wird durch die Urlaubszeit über Weihnachten leider etwas dauern.

**Comment by fjbender** [comment]
Mit dem commit 3bc761b36af232ec211fcea556b41b9efe89bdac im Branch [AboCommerce-recurringAction-compatibility](https://github.com/PAYONE-GmbH/shopware-5/tree/AboCommerce-recurringAction-compatibility) konnte ich bei mir lokal erfolgreich Kreditkarten-Abos einziehen.

Könnt ihr auch nochmal testen?

**Comment by JensPetersRhiem** [comment]
Danke für die Rückmeldung, das werde wir umgehend testen.

**Comment by fjbender** [comment]
Werden wir mit #50 mergen.

@JensPetersRhiem habt ihr schon Feedback?

**Comment by JensPetersRhiem** [comment]
Die Abo-Bestellungen konnten erfolgreich durchgeführt werden! Vielen Dank!
