### ISSUE TITLE
Improvement of external API functions

### ISSUE THREAD

**Issue by lherbst** [PAYONE-GmbH/shopware-5#44]
Hi,
we currently have a project which needs us to capture pre-authorized order amounts automatically once the shop owner sends a shipping confirmation of the order to the shop.

The external API functions requested in #32 seemed to be exactly what we needed.
However, we found three drag-downs in the current implementation:

The described "quantity" is not working for the $orderDetailParams parameter. Passing the amount is mandatory at the moment.

Each exception thrown in the captureOrder() method is getting echoed. Is this intended? We would need output buffering to get those exception texts.

The parameter $includeShipment does not seem to have any effect. The variable is not being used in the buildCustomOrderCapture() method of the Parambuilder.

**Comment by fjbender** [comment]
Yes, these methods still lack proper documentation :( 

The exception being echoed is also not ideal, I see that. However, current implementations rely on the captureOrder() not throwing any exceptions. We'll have to make sure that migration goes smoothly.

I'll look into the parameters as soon as I have proper documentation for the input parameters from Dev.

**Comment by fjbender** [comment]
We will add proper documentation and remove the echoed Exceptions.

@lherbst can you provide a test scenario for the non-working parameters, i.e. a script? The $includeShipment parameter is passed on to buildCustomOrderCapture, and then finally to getParamCustomAmount in the ParamBuilder where it's used.

**Comment by lherbst** [comment]
Please find attached the screenshot of the current implementation of buildCustomOrderCapture we use in the shop (plugin version is 3.4.0_5908):
![buildcustomordercapture](https://cloud.githubusercontent.com/assets/12892280/20960499/fec6dece-bc60-11e6-8392-1d9277d6b4a5.png)

Conveniently, PhpStorm highlights the parameter $includeShipment grey, which means the variable is not used at all.

However, as I can see in the current version on GitHub the implementation changed. There is no method getParamCustomAmount available in our current Plugin-Code. Will this be delivered in a future plugin version?

**Comment by fjbender** [comment]
Oh, sorry, I didn't notice you weren't using the current version from Github. We'll upload a new version to the Shopware Community Store with the updated implementation as soon as the inline code documentation is included as well.

I'd say this issue will be resolved then. Can you test again in the v3.4.4 available at https://github.com/PAYONE-GmbH/shopware-5/releases?

**Comment by lherbst** [comment]
Yes, the issue concerning $includeShipment is indeed resolved with this.

However, the two other topics I mentioned would still be relevant; you already said that the echoed exceptions will be removed, can you also give any info on the last topic?

**Comment by fjbender** [comment]
Not yet - I'm waiting for the documentation on what is expected to be in the $orderDetailsParams array, so I can properly test it.

**Comment by lherbst** [comment]
We now switched to v3.4.4 and started to use the captureOrder() method.

However, we found a few bugs which still seem to need some fixing. Do you want me to put them here or in a different issue?

Additionally, after fixing those bugs temporarily by ourselves we were able to execute the method, however it returned false without giving any info in the logs. I maybe should mention that we use it in a Shopware Console-Command.

**Comment by fjbender** [comment]
Please open a separate issue for the bugs. Ideally, you'll open a pull request with your suggestions to fix the bugs.

Concerning the method just returning false: Please contact me at integrations@payone.de so I can take a closer look. I wanna rule out a plattform issue first.

**Comment by lherbst** [comment]
Hi,

can you give us any updates regarding this topic?

**Comment by fjbender** [comment]
Hi, sorry, we can't give you anything new just yet.

**Comment by fjbender** [comment]
Fixed with pull request #64
