### ISSUE TITLE
Support for Customer Management API calls

### ISSUE THREAD

**Issue by M-arcus** [PAYONE-GmbH/shopware-5#445]
SA - Customer management (updateuser):
https://docs.payone.com/pages/releaseview.action?pageId=1213913

SA - Customer management (getuser):
https://docs.payone.com/pages/releaseview.action?pageId=1213926

**Comment by jvarelmann** [comment]
Hello Marcus,

do you have any questions about our API ?

regards Juergen

**Comment by M-arcus** [comment]
Hello Juergen,

In some cases, the customer executes a payment, changes his data, then executes another payment (sometimes those get executed automatically). This can lead to cases where a user has different data in Shopware 5 and PayONE. This can be confusing for the customer, since mails get both sent from Shopware 5 and PayONE with different addresses.

Regards Marcus

**Comment by jvarelmann** [comment]
Hello Marcus,

all booking related Informations should be provided via Api to us during the checkout. This informations should be same in our system and in the shopware backend.

the two API you mentioned are only used by recurring payments not for normal bookings

regards Juergen

**Comment by M-arcus** [comment]
Hello Juergen,

correct, there are recurring payments being used in the Shopware 5 Shop.

Regards Marcus

**Comment by jvarelmann** [comment]
Hello Marcus,

this plugin is not really build for recurring payment and only slidly compatible with abocommerce. So it depence in witch way the recurring payment was created and where the plan is hosted. if it is hostet in our system you can use the mentioned API. If the plan is hosted in the shopware shop you provides us with all information from your system and there is no differences between the the two systems

regards Juergen
