### ISSUE TITLE
Klarna Error in Shipping/Payment

### ISSUE THREAD

**Issue by mwillner** [PAYONE-GmbH/shopware-5#458]
Sometimes `me.data` is undefined in:

https://github.com/PAYONE-GmbH/shopware-5/blob/6bf250393c76b0cd0d1003fe5258397a74e36ecd/Frontend/MoptPaymentPayone/Views/frontend/_resources/javascript/mopt_klarna_shipping_payment.js#L62

In this case, a js error will by thrown and some functions in the checkout do not work as intended.
E.g. getting "Invalid token"-Errors when proceeding, after changing the payment method.

Please make sure to check whether `me.data` is not undefined before trying to access its properties.

**Comment by jvarelmann** [comment]
Hello,

we haven heard about this error what is the behavoir when this error occours? 
can you descripe the error in a bit more detail. so that we can test it Please.

regards Juergen
