### ISSUE TITLE
Payment method PayPal does not get shown on account payment page

### ISSUE THREAD

**Issue by M-arcus** [PAYONE-GmbH/shopware-5#462]
Plugin Version 4.7.0

Payment method PayPal is no longer visible under “/account/payment” after updating to 4.7.0.   
It's still visible and selectable during checkout.

**Comment by jvarelmann** [comment]
Hello Marcus,

looks like there is something gone wron during the installation, try to deinstall the plugin and reinstall it

regrads Juergen

**Comment by M-arcus** [comment]
Downgrading the plugin to the previous version solves the issue.
Are there checks that were added to PayPal in the new version?

**Comment by M-arcus** [comment]
PayPal disappears after commit occurs after the commit c615a06592993a3f21a5f2a074b70cc95b2cb7eb (a merge commit, because pull request https://github.com/PAYONE-GmbH/shopware-5/pull/440 was accepted there).
PayPal gets included in the array of payment methods that don't get shown in the account page.

Please include an option to configure this. 
Some customers are confused on why certain payment method have gotten removed.

**Comment by hreinberger** [comment]
Hi @M-arcus I've just tested and merged your PR #463 thx!

**Comment by hreinberger** [comment]
PS: a little background. The PAYMENTS_EXCLUDED_FROM_ACCOUNTPAGE array exists to filter out express and installment payment methods from the favorite payment methods page. The UX flow for these payment methods only works when there's already a filled shopping cart to invoke the express checkout or installment calculation.
