### ISSUE TITLE
Bugs in external API functions

### ISSUE THREAD

**Issue by lherbst** [PAYONE-GmbH/shopware-5#48]
Hi,

while using the external API function captureOrder of the Plugin-Bootstrap we came across a few bugs / exceptions / deprecated calls:

- "Missing argument 2 for Doctrine\ORM\QueryBuilder::from()" in .../Frontend/MoptPaymentPayone/Models/MoptPayoneConfig/Repository.php on line 22
- "Undefined variable: invoicing" in .../Frontend/MoptPaymentPayone/Bootstrap.php on line 1055
- "Undefined index: payolution_b2b" in .../Frontend/MoptPaymentPayone/Bootstrap.php on line 1153
- "Shopware()->__call(MoptPayoneBuilder) is deprecated since version 4.2 and will be removed in 5.3. Use the Container instead" in .../Frontend/MoptPaymentPayone/Bootstrap.php on line 1143

The following exception is thrown if you ignore the deprecated warning above. However, it is only thrown when used in a Shopware Console-Command:
- "Method "Shopware::MoptPayoneBuilder" not found failure" in .../Frontend/MoptPaymentPayone/Bootstrap.php on line 1143

Additionally, it seems like the taxes of the shippings costs are not calculated correctly if you compare the two methods getParamCaptureAmount and getParamCustomAmount of the Mopt_PayoneParamBuilder class.

**Comment by fjbender** [comment]
@lherbst which revision of the plugin are you using? Your line numbers seem to be a little off and some of the issues I can't find at all. Can you confirm the issues in the current version?

**Comment by lherbst** [comment]
We are using v3.4.4 from https://github.com/PAYONE-GmbH/shopware-5/releases in Shopware Version 5.2.9.

I double-checked the line numbers and they seem to be fitting comparing to the 3.4.4 release.

**Comment by fjbender** [comment]
Alright, thanks. I was comparing to current HEAD of master.

@Fatchip-Support please add this to the backlog.

**Comment by lherbst** [comment]
Hi,

can you give us any updates regarding this topic?

**Comment by fjbender** [comment]
Also, we don't have anything new here for the moment. :(

**Comment by fjbender** [comment]
Fixed with pull request #64.
