### ISSUE TITLE
PayOne prepayment - 4 developers failed to implement BookingID in PDF

### ISSUE THREAD

**Issue by nna21** [PAYONE-GmbH/shopware-5#69]
Liebe Kollegen,
 
insgesamt 4 Entwickler haben einen Tag lang vergeblich versucht, Verwendungszweck / Usage die Variable {$sBookingID} für die Zahlungsart PayOne Prepayment einzubinden. Es gelang uns zwar zuerst im Finishing (Ansicht im Checkout, nachdem Zahlung abgeschlossen wurde), aber beim Versuch, die BookingID auch im Druckansicht-PDF (aus dem Finishing erzeugt) und in der von Shopware automatisch generierten Rechnung einzubinden, sind wir gescheitert.
 
Eine letzte Rückmeldung unserer Entwickler ist: Finish page is using the third snippet from your screenshot.png (FinishPayinadvanceData, as I already wrote before), so it uses {$sBookingID} variable. 
PDF generated in admin (EN invoice pdf.png) uses the first snippet from screenshot.png, so it's once again with {$sBookingID} that once again returns nothing.
I guess it's better to ask the other developer why this variable doesn't show anything.

Gibt es hierzu eine Lösung, bzw. könnte es so dokumentiert werden, dass erfahrene Shopware-Entwickler in der Lage sind, dies zu implementieren?

**Comment by fjbender** [comment]
Hallo, 

bei Vorkasse kann die TX-ID (Verwendungszweck) auch über `{$Order._order.transactionID}` im PDF Rechnungstemplate geholt werden.
