### ISSUE TITLE
Payolution Fehlermeldung!!!

### ISSUE THREAD

**Issue by Emin3m** [PAYONE-GmbH/shopware-5#95]
Ich mach mal in deutsch :-)

In der Datei MoptPaymentPayone (Frontend Controller) ist die Funktion **payolutionErrorAction** (ca. Zeile 985) anders aufgebaut als die Funktion danach **ratepayErrorAction** was dazu führt, dass bei Fehlermeldungen durch den Zahlungsanbieter Payolution immer nur die gleiche nichts aussagende Fehlermeldung "Es ist ein Fehler aufgetreten" ausspuckt wird. Ich habe die wie folgt geändert:

`$session = Shopware()->Session();
        $errorCode = $session->payolutionErrorCode;
        $errorMessage = $session->payolutionErrorMsg;
        $this->View()->errormessage = Shopware()->Snippets()->getNamespace('frontend/MoptPaymentPayone/errorMessages')->get('errorMessage'.$errorCode, $errorMessage.' (Fehler '.$session->payolutionErrorCode.')', true);
`
und dementsprechend in Zeile 694 

`$this->forward('payolutionError')`

ersetzt durch

'$session->payolutionErrorCode = $response->getErrorcode();
            $session->payolutionErrorMsg = $response->getCustomermessage();
            $this->forward('payolutionError');'

solltet ihr mal offiziell machen :-)

vor dieser Änderung wurden die Payolutionfehler auch nicht in den Api-Logs geloggt, das scheint nun aber zu gehen!?

**Comment by T-Kuchel** [comment]
i forwarded this issue to @FATCHIP-GmbH and keep you informed on progress.

**Comment by fjbender** [comment]
Solved with #99
